### ISSUE TITLE
Viewing events & signing in blocked by error

### ISSUE THREAD

**Issue by lorelei1** [wearekickback/app#157]
When I go to a direct event link, or try to view events from the kickback home page, i get this red banner:
"Error: Network error: Response not successful: Received status code 400"
Click sign in and after ~3 seconds of showing the sign in form, it reverts to the same banner. 
<img width="953" alt="Screen Shot 2019-08-15 at 9 54 47 AM" src="https://user-images.githubusercontent.com/38163206/63111540-c24bb900-bf42-11e9-96af-e063a7a00d00.png">

I am signed into main net.

**Comment by skylarweaver** [comment]
Thanks @lorelei1! What's the browser you are using? And with Metamask?

@makoto Not sure if this is something you've seen before.

**Comment by makoto** [comment]
I think this was temporary error on server side
