### ISSUE TITLE
Create account page gives graphql error

### ISSUE THREAD

**Issue by jefflau** [wearekickback/app#219]
Reproduction:

1) Mac OS 10.14 Brave/Metamask installed (but not used)
2) Click login and select authereum
3) Select account (mine seems to automatically know my authereum account now)
4) Create page for account pop up
5) GraphQL login error and account not created

<img width="1256" alt="Screenshot 2019-12-09 at 14 48 24" src="https://user-images.githubusercontent.com/1221141/70413785-3599ad80-1a93-11ea-8d43-91487190a10e.png">

**Comment by shanefontaine** [comment]
The issue here seems to be that the address being used has already been used to create an account. Does this behavior look familiar to you and/or do you understand why this page would appear for an account that already exists in the DB?

**Comment by makoto** [comment]
This is already fixed at Authereum end
