### ISSUE TITLE
create event page (kovan) does not load

### ISSUE THREAD

**Issue by NukeManDan** [wearekickback/app#222]
https://kovan.kickback.events/create

spinner continues forever, no console errors reported.
- Manjaro Linux
- Mozilla Firefox 71.0
- privacy & security features turned off 

All other pages seem to work, including account creation

**Comment by NukeManDan** [comment]
https://kickback.events/create

this does load, with same settings 

BUT: URL was specified manually, no "new event" button exists on the main app I can see.

**Comment by makoto** [comment]
Sorry, fixed now.
For any problem like this, feel free to ping me via discord https://discord.gg/C2HuhU
