### ISSUE TITLE
Create event page nvaigation & new events not shown

### ISSUE THREAD

**Issue by NukeManDan** [wearekickback/app#226]
First issue: I cannot find a way to create an event in the GUI for the app  - I must navigate manually to `/create`

Second, once I do get an event created:
![image](https://user-images.githubusercontent.com/35669742/70869821-e26ba300-1f49-11ea-8012-c0860f27e932.png)
I then don't see it.

I generated a transaction ([on kovan](https://kovan.etherscan.io/tx/0x729a53402c1cb0f8e92d77f3b5ebf6a336c2d474490709f6f587f99cc02d614f) but the event page does not display on `http://localhost:3000/event/0x71646dC2f4960f74554D3eF98301582522046793`

Also not on `https://kovan.kickback.events/event/0x71646dC2f4960f74554D3eF98301582522046793`

**Comment by makoto** [comment]
Our new event page is not public hence no link yet.
For others, it should be working by now,
