### ISSUE TITLE
Implement comment sections on events (with 3box?)

### ISSUE THREAD

**Issue by TomAFrench** [wearekickback/app#255]
If we compare Kickback to its competitor Meetup, its very difficult to contact an event organiser before an event. This is useful to be able to ask questions beforehand, etc. Otherwise it can feel a little impersonal and possibly creating a barrier to entry.

One possible decentralised solution would be to use [3box](https://docs.3box.io/build/plugins/comments).

**Comment by makoto** [comment]
That's a great suggestion. I was thinking about doing something similar but as an alternative to telegram and can access to only people who have RSVPed. Whenever I sign up for the event, I ended up signing up their telegram channel. If we create some sort of plugin which only allows people who did RSVP on Kickback to see the message or comment, that would be cool way to prevent spams as well.

**Comment by TomAFrench** [comment]
A couple of issues with 3box are that comment section can only have one administrator address (iffy scaling to multiple admins) and to limit the comments to only people signed up for the event would require the admin to manually accept each one.

**Comment by makoto** [comment]
`limit the comments to only people signed up for the event would require the admin to manually accept each one` this sounds like more of the blocker.

**Comment by makoto** [comment]
Actually we could somehow automate it. The admin still have to accept but we can hit Kickback API to check if the request came from the one who did RSVP on Kickback, 

I just wrote a spec at https://github.com/wearekickback/app/issues/267 . Any feedback welcome.

**Comment by makoto** [comment]
I will close this issue as it is duplicate to 267
