### ISSUE TITLE
Submission of work

### ISSUE THREAD

**Issue by bobeu** [wearekickback/app#264]
Here is[ link](https://medium.com/@imeiwall/how-kickback-can-help-spice-up-your-event-and-prevent-event-disasters-3a8701605b29) to article on medium. Click [here](https://medium.com/@imeiwall/how-kickback-can-help-spice-up-your-event-and-prevent-event-disasters-3a8701605b29).

**Comment by makoto** [comment]
I will close this as  I see that you submitted it through https://github.com/wearekickback/app/issues/235
