### ISSUE TITLE
Fix inaccurate warning on Approve button

### ISSUE THREAD

**Issue by TomAFrench** [wearekickback/app#268]
Copying this from #263 

## Description

Currently when a user is using a web3 enabled browser but hasn't given metamask access to kickback.events the Approve button shows the below error message.

![](http://i.imgur.com/nGIOmWx.png)

A complaint about insufficient balance is obviously not ideal as the user may have the required balance, leading to confusion.

## Submission requirements

A check should be placed on the Approve button which in the case of the user not being logged in, displays a button with the text "Log in to RSVP" in its place. This button should be functionally identical to the "Sign in" button on the header except for styling.

**Comment by andygray** [comment]
Agree with the issue.

Need to understand the difference between having a balance of DAI and not having approved DAI.

The UX need to explain that two transactions will happen - one for approval and one to move the DAI to kickback. 

Having disabled buttons and red box leads to confusion and not knowing what to click and fear of doing so.

**Comment by makoto** [comment]
Fixed at https://github.com/wearekickback/app/pull/277
