### ISSUE TITLE
Post multi wallet support (aka onboard.js) issues

### ISSUE THREAD

**Issue by makoto** [wearekickback/app#298]
- No "Metamask" on mobile window
- Red warning when not connected into ethereum node should say "Connect to wallet".

**Comment by TomAFrench** [comment]
> No "Metamask" on mobile window

https://github.com/blocknative/onboard/pull/198

**Comment by TomAFrench** [comment]
> Red warning when not connected into ethereum node should say "Connect to wallet".

Related to this... It's probably worth mentioning the hosted wallets like Authereum as an option if people don't want to install an extension/app in the "getting started" guide

**Comment by makoto** [comment]
@TomAFrench we will be wireframeing new onboarding flow based on various feedback we got. Will share once ready.
